server:
  port: 8881
spring:
  datasource:
    url: jdbc:postgresql://maqshost:5432/movielens
    username: postgres
    password: postgres
    initialize: false
    driver-class-name: org.postgresql.Driver
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      poolName: SpringBootJPAHikariCP
      maxLifetime: 2000000
      connectionTimeout: 10000
  jpa:
    show-sql: true
    database: postgresql
    hibernate.ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        id.new_generator_mappings: false
        format_sql: true
        enable_lazy_load_no_trans: true
logging:
  level:
    org.hibernate: INFO
    org.springframework: INFO
logging.level.com.maqs: DEBUG
